GET http://localhost:3333/products

###

POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "image_url": "https://via.placeholder.com/150",
  "price": 100
}

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "username": "maby",
  "password": "maby"
}

###

GET http://localhost:3333/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFieSIsImlhdCI6MTcwNzA1MjM2OCwiZXhwIjoxNzA3MDUyNDI4fQ.2vNKzJe-NmzeMVAXhPQGWTaiOKuC9wEcV_O-Qo1DkHs

###

GET http://localhost:3333/orders/a038dc06-8086-4ad2-86d4-adedef7da481
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFieSIsImlhdCI6MTcwNzA1MjM2OCwiZXhwIjoxNzA3MDUyNDI4fQ.2vNKzJe-NmzeMVAXhPQGWTaiOKuC9wEcV_O-Qo1DkHs

###

POST http://localhost:3333/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWFieSIsImlhdCI6MTcwNzA1MjM2OCwiZXhwIjoxNzA3MDUyNDI4fQ.2vNKzJe-NmzeMVAXhPQGWTaiOKuC9wEcV_O-Qo1DkHs

{
  "items": [
    {
      "product_id": "04c4353a-3f6d-4272-a8f2-44b82c05ecc0",
      "quantity": 1
    },
    {
      "product_id": "0afa7630-4fc1-4d69-beed-4f8f15becadc",
      "quantity": 1
    }
  ],
  "card_hash": "123"
}